### ISSUE TITLE
yaml_files and yaml_directories Resource precondition failed even if resource meets condition

### ISSUE THREAD

**Issue by lonix77** [netascode/terraform-mso-nac-ndo#30]
Below error encountered even if both variable contain values. Example:
yaml_files = ["data/ndo.yaml"] 
or
yaml_directories = ["data"]  

│ Error: Resource precondition failed
│
│   on merge.tf line 21, in data "utils_yaml_merge" "model":
│   21:       condition     = length(var.yaml_directories) != 0 || length(var.yaml_files) != 0 || length(keys(var.model)) != 0
│     ├────────────────
│     │ var.model is empty map of dynamic
│     │ var.yaml_directories is empty list of string
│     │ var.yaml_files is empty list of string
│
│ Either `yaml_directories`,`yaml_files` or a non-empty `model` value must be provided.

**Comment by danischm** [comment]
Could you share the full module configuration you are using?

**Comment by lonix77** [comment]
[code.zip](https://github.com/netascode/terraform-mso-nac-ndo/files/15452578/code.zip)
i uploaded my test environment files

**Comment by andbyrne** [comment]
You are not using the module correctly. You should only have a single main.tf file and your data folder. Don't clone the repository.

This is all your main.tf needs to contain:

```
terraform {
  required_providers {
    aci = {
      source = "CiscoDevNet/mso"
    }
  }
}

provider "mso" {
  username = "admin"
  password = "xxxxx!"
  url      = "https://x.x.x.x:8443"
  platform = "nd"
}

module "nac-ndo" {
  source  = "netascode/nac-ndo/mso"
  version = ">= 0.8.1"

  yaml_files = ["data/ndo.yaml"]
  #yaml_directories = ["data"]  


  manage_schemas = true
  manage_sites   = false
  manage_tenants = true
}
```
